from __future__ import annotations

import typing
import logging

import pint
import pint_pandas
import pydantic
import pydantic.fields

if typing.TYPE_CHECKING:
    from typing import Any
    from pydantic.typing import AbstractSetIntStr, MappingIntStrAny, NoArgAnyCallable

logger = logging.getLogger(__name__)

# Apply the same UnitRegistry and definitions as in hfATLAS
try:
    # Try to use the registry already configured by hfATLAS
    from hfATLAS.units import ureg
    logger.info("Successfully linked to hfATLAS unit registry.")
except ImportError:
    # Create a registry and load the critical definitions manually.
    # This ensures the package works even if hfATLAS is not installed,
    # preventing crashes on units like 'cms' or 'fraction'.
    logger.warning(
        "hfATLAS not found. Falling back to local UnitRegistry with hfATLAS definitions."
        "Install hfATLAS from https://github.com/lynker-spatial/hydrofabricATLAS"
        )
    ureg = pint.UnitRegistry()
    
    # Inline definitions based on hfATLAS/units.txt to ensure compatibility
    _custom_defs = [
        "cfs = cubic_feet / second = ft3/s",
        "cms = cubic_meter / second = m3/s",
        "fraction = 1 = frac",
        "pct = percent = percentage",
        "decimal_degree = dd",
        "ha = hectare",
        "thermal_conductivity_units = watt / meter / kelvin = W_m_K",
        "specific_heat_units = kilojoule / kilogram / degC = kJ_kg_C",
        "ppfd = micromole / meter**2 / second = umol_m2_s"
    ]
    
    for definition in _custom_defs:
        try:
            ureg.define(definition)
        except pint.DefinitionSyntaxError as e:
            logger.error(f"Failed to define unit '{definition}': {e}")
            pass

# Allowing pint_pandas to read Parquet files generated by hfATLAS.
pint.set_application_registry(ureg)
pint_pandas.PintType.ureg = ureg

class UnitAwareFieldInfo(pydantic.fields.FieldInfo):
    """
    Thin wrapper around a `pydantic.fields.FieldInfo` that adds unit information.
    """

    def __init__(self, unit: str | pint.Unit):
        if isinstance(unit, str):
            try:
                ureg.parse_units(unit)
            except pint.UndefinedUnitError as exc:
                raise ValueError(
                    f"Unit '{unit}' is not defined in the shared registry. "
                    "Ensure hfATLAS definitions are loaded."
                ) from exc
        super().__init__(units=unit)

    def __call__(
        self,
        default: Any = pydantic.fields.Undefined,
        *,
        default_factory: NoArgAnyCallable | None = None,
        alias: str | None = None,
        title: str | None = None,
        description: str | None = None,
        exclude: AbstractSetIntStr | MappingIntStrAny | Any | None = None,
        include: AbstractSetIntStr | MappingIntStrAny | Any | None = None,
        const: bool | None = None,
        gt: float | None = None,
        ge: float | None = None,
        lt: float | None = None,
        le: float | None = None,
        multiple_of: float | None = None,
        allow_inf_nan: bool | None = None,
        max_digits: int | None = None,
        decimal_places: int | None = None,
        min_items: int | None = None,
        max_items: int | None = None,
        unique_items: bool | None = None,
        min_length: int | None = None,
        max_length: int | None = None,
        allow_mutation: bool = True,
        regex: str | None = None,
        discriminator: str | None = None,
        repr: bool = True,
        **extra: Any,
    ) -> typing.Any:
        """
        Turn the UnitAwareFieldInfo into a pydantic.fields.FieldInfo.
        Use like pydantic.fields.Field function (same method signature).
        """
        return pydantic.Field(
            default=default,
            default_factory=default_factory,
            alias=alias,
            title=title,
            description=description,
            exclude=exclude,
            include=include,
            const=const,
            gt=gt,
            ge=ge,
            lt=lt,
            le=le,
            multiple_of=multiple_of,
            allow_inf_nan=allow_inf_nan,
            max_digits=max_digits,
            decimal_places=decimal_places,
            min_items=min_items,
            max_items=max_items,
            unique_items=unique_items,
            min_length=min_length,
            max_length=max_length,
            allow_mutation=allow_mutation,
            regex=regex,
            discriminator=discriminator,
            repr=repr,
            **self.extra,
            **extra,
        )


def Unit(unit: str | "pint.Unit") -> Any:
    """
    Return a type-erased UnitAwareFieldInfo.

    Example:
        class Foo(pydantic.BaseModel):
            bar: int = Unit("meter")
    """
    return UnitAwareFieldInfo(unit)


def _unit(unit: str) -> tuple[UnitAwareFieldInfo, Any]:
    """
    Return a UnitAwareFieldInfo and type erased UnitAwareFieldInfo from a str.


    Example:
        MeterField, Meter = _unit("meter")

        class Foo(pydantic.BaseModel):
            bar: int = Meter # type checker happy
            baz: int = MeterField(default=42) # type checker happy

            quox: int = Meter(gt=0) # type checker sad, but works
    """
    field = UnitAwareFieldInfo(unit=unit)
    return field, field


# Common units
MeterField, Meter = _unit("meter")
SecondField, Second = _unit("second")
KelvinField, Kelvin = _unit("kelvin")
DimensionlessField, Dimensionless = _unit("dimensionless")
